### ISSUE TITLE
[Question] Communication means

### ISSUE THREAD

**Issue by ghost** [3x8/nostromo#3]
Hi! Do you have any other communication means except for github issues? Like some forum, discord server or telegram channel?
I am super excited after finding this awesome project but it looks like there is no documentation...
I want to test it on my tricopter with [SucceX 50A v2](https://www.getfpv.com/iflight-succex-50a-v2-slick-2-6s-esc-2-pcs.html), but I'm not sure if it's the same device as SUCCEX50AV2 target. Do I have to replace stock BLHeli32 bootloader with costaguana? And if yes, is it possible to backup original one? Should I do it with STLink or maybe it's possible to reflash the BL without external swd debugger? Any docs or notes would be awesome!
Thanks!

**Comment by adrianmiriuta** [comment]
@Unb9rn 
this is more a private repository for my own ideeas and tweaks (I have no forum, discord, telegram, facebook ...)

if you are not very deep !!! in ESC programming 

you should use :
https://github.com/AlkaMotors/AM32-MultiRotor-ESC-firmware

This sould be usefull : 
https://www.rcgroups.com/forums/showthread.php?3322857-A-cheap-32-bit-diy-ESC-and-firmware

1. It is the right target for the ESC,  but it's not a optimized target (due to hardware design flaws) 
    I would recomand RAZOR32V2
    https://www.banggood.com/de/4-PCS-Razor32-V2-35A-BL_32-3-6S-DShot1200-Brushless-ESC-w-or-RGB-LED-and-Current-Sensor-for-RC-Drone-p-1621601.html

2. You cannot backup blheli32 bootloader as it is read/write protected and encrypted
3. No It's not possible to go back to blheli32
4. Yes you need to replace the bootloader 
  HowTo (https://www.rcgroups.com/forums/showpost.php?p=42667001&postcount=120)
5. No, you need a STLINKv2

**Comment by ghost** [comment]
Those ESCs are already installed and the craft has somewhat thin arms (like 12 mm wide). Should I expect some major issues with succex or switching to Razors is must-have? (this is not a racing quad-it's more like exploratory tricopter with a bunch of FOSS software and hardware after all) 
Anyway, good luck with this project, I hope it'll get some community soon =) I think we all need open source ESC firmware. Will Check this AM32 you suggested too.
Thanks!=)

**Comment by adrianmiriuta** [comment]
@Unb9rn

1. the 50A are overrated
2. they are very noisy 
3. BEMF rc divisor, somewhat unhappy choice 
4. u,i telemetry inaccurate
5. 1K resistor in input line (i changed it to 50 OHM)
6. my firmware is a fork of ALKAM AM32 (optimized for LOS acrobatic and PROSHOT1000 protocol)

THX.

**Comment by ghost** [comment]
Well, thanks once again! Closing this issue.
